name: tlucalendar
description: "TLU Calendar for TLU students"
publish_to: 'none'
version: 2025.11.12

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  http: ^1.6.0
  dio: ^5.9.0
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  android_intent_plus: ^6.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  android_alarm_manager_plus: ^5.0.0  # For exact daily alarms

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
